#!groovy

// Generated by IBM TransformationAdvisor
// Tue Apr 09 14:15:18 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}