#!groovy

// Generated by IBM TransformationAdvisor
// Mon Apr 08 16:28:30 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}