#!groovy

// Generated by IBM TransformationAdvisor
// Tue Jan 15 11:06:59 EST 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'senderwar'
    mvnCommands = '--version'
    test='false'
}